# Generated by Django 4.1.7 on 2024-02-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_is_admin_usuario_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pwd',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
