# Generated by Django 4.1.7 on 2024-02-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ejercicio_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
